### ISSUE TITLE
How to use them? 

### ISSUE THREAD

**Issue by Evanndr** [RAMDRAGONS/Splatoon-FesData#4]
How can we use this data on splatoon 3?

**Comment by RAMDRAGONS** [comment]
I don't believe there's a public method to use the data in any end-user form currently, it would most likely require a server reimplementation akin to Wiimmfi or Pretendo to serve it (modified to account for the new dates you'd want to run the Splatfest on) to users connecting to the specific instance of the custom server.

**Comment by Cuphead74832** [comment]
> How can we use this data on splatoon 3?

Hey man just wrote a tutorial under the issues on how you can recover data textures. Check the issues tab again.
