### ISSUE TITLE
Attempt to recreate data (Previous Name: Need help using data)

### ISSUE THREAD

**Issue by Cuphead74832** [RAMDRAGONS/Splatoon-FesData#5]
Hey i need help? I wonder how do i import this into my console. I got a MOD that triggers splatoon into thinking its splatfest day 2 but team does not show up! I need help as i tried to use my own data. So how to import the uploaded data back onto a switch thats in here.

Also it would be nice if someone sends screenshots of them actually getting the teams to show up. Because booting into CFW is a heavy backpack everytime as its mostly on normal mode.

-- IDEA SEPARATED FROM QUESTION --
It would be cool too if there is a COMPLETE .nro payload for importing splatfest easily by downloading the folder of the one you want and then selecting it with the tool. Or maybe since the console need internet a way to trick splatoon 3 into its connected and show the collected data happens (which i already got to trick the game via patches but no luck with team names).

**Comment by Coxxs** [comment]
As mentioned in [#1](https://github.com/RAMDRAGONS/Splatoon-FesData/issues/4#issuecomment-1510009884), unfortunately, there is no public method to load the data into the game right now

**Comment by Cuphead74832** [comment]
Im in my way of setting Switch ToolBox on my PC. If there are single textures of the splatfest in the decrypted it then you know with just homebrew it is eventually retexturization might work as it is easier. If i get toolbox on linux of course for now i am downloading and if i success finding interesting stuff i will post it here

**Comment by Cuphead74832** [comment]
![Screenshot 2024-01-16 14 09 44](https://github.com/RAMDRAGONS/Splatoon-FesData/assets/119815517/b540d5b7-b726-4b90-ae03-ce65f338fd01)

It seems like there is a texture file in base im using the latest splatfest (family vs friends vs solo) and there is this file in the model folder. But is in the stupid .zs format so its probably encrypted any ideas????

-- FOR NEWBIES THAT ENTERED THE THREAD AND WANNA RECREATE MY STEPS--
Are you a fellow traveler that knows about this and just read this comment?
If you know about this get a tool called SwitchToolBox https://github.com/KillzXGaming/Switch-Toolbox
Download the base from decrypted from Splatoon 3 Family vs Friends vs Solo
Extract the .zs file using SwitchToolBox
You are now in the same stage i am. If you make any progress please let everyone know in this thread.

**Comment by Cuphead74832** [comment]
-- CURRENT PROGRESS OF MINE IS IN THIS SINGLE COMMENT --
Found about: https://github.com/mcmilk/7-Zip-zstd/releases/tag/v22.01-v1.5.5-R3
Trying wine.
Success now i have a .bfres file
Also found: https://github.com/LordNed/BFRES-Extractor
Trying...
Big issue i cant use .sln files in my linux install so if someone can do it for me and pass me a download it would be cool. It may be a visual studio file you have to compile.
Found new tool: https://github.com/aboood40091/Embedd-Extractor/releases/tag/v0.1

**Comment by Cuphead74832** [comment]
BFRES "Embedded Files" Extractor v0.1
(C) 2017 Stella/AboodXD
Unable to recognize the BFRES file!

That is what my terminal says well i give up its hard maybe the previous tool would work but i cant try it. If someone else can try it for me please tell me and how to set it up on my pc.

**Comment by Cuphead74832** [comment]
OKAY NEW PLAN! Im gonna close this issue and open a new one soon explaining what to do.
