### ISSUE TITLE
What is the decrypted for?

### ISSUE THREAD

**Issue by Cuphead74832** [RAMDRAGONS/Splatoon-FesData#6]
What is the "decrypted" data mean and how can it be used?

**Comment by Coxxs** [comment]
You can use https://github.com/KillzXGaming/Switch-Toolbox to view the content

**Comment by Cuphead74832** [comment]
Nice! 

> You can use https://github.com/KillzXGaming/Switch-Toolbox to view the content


If i obtain my own data can same tool decrypt?
