### ISSUE TITLE
Tutorial: How to use the decrypted data to recover textures. (DO NOT CLOSE)

### ISSUE THREAD

**Issue by Cuphead74832** [RAMDRAGONS/Splatoon-FesData#7]
In this case we will use the splatfest data to reobtain our tee shirt

1. Download SwitchToolBox
2. Download the Decrypted splatfest data you want to get
3. Extract the SwitchToolBox
4. Open the base.pack of the decrypted data via the ToolBox (located in ToolBox.exe of the extracted asset)
5. Find the textures folder and open it
6. Extract the .bfres.zs file inside it by right clicking it
7. Restart the tool as this file might crash it due to overloading
8. Open the .bfres.zs file you might get an error message of the tool this mean is about to crash
9. Quickly extract the textures folder by right clicking it and export. The tool will crash upon exporting. If it does not close it because it will.
10. Open the tool again and the exported file.
11. You succesfully dumped the textures files just right click the one you want and Export.

Now you can patch the tee shirt texture (NOT TESTED YET BY ME) and have your shirt back.

**Comment by Coxxs** [comment]
Thanks for sharing. It's possible to double click on the .zs file in the latest toolbox to open it.
